var annotated_dup =
[
    [ "BarPlotSeries", "struct_bar_plot_series.html", "struct_bar_plot_series" ],
    [ "BarPlotSettings", "struct_bar_plot_settings.html", "struct_bar_plot_settings" ],
    [ "BooleanArrayReference", "struct_boolean_array_reference.html", "struct_boolean_array_reference" ],
    [ "BooleanReference", "struct_boolean_reference.html", "struct_boolean_reference" ],
    [ "CharacterReference", "struct_character_reference.html", "struct_character_reference" ],
    [ "Chunk", "struct_chunk.html", "struct_chunk" ],
    [ "DynamicArrayNumbers", "struct_dynamic_array_numbers.html", "struct_dynamic_array_numbers" ],
    [ "IHDR", "struct_i_h_d_r.html", "struct_i_h_d_r" ],
    [ "LinkedListCharacters", "struct_linked_list_characters.html", "struct_linked_list_characters" ],
    [ "LinkedListNodeCharacters", "struct_linked_list_node_characters.html", "struct_linked_list_node_characters" ],
    [ "LinkedListNodeNumbers", "struct_linked_list_node_numbers.html", "struct_linked_list_node_numbers" ],
    [ "LinkedListNodeStrings", "struct_linked_list_node_strings.html", "struct_linked_list_node_strings" ],
    [ "LinkedListNumbers", "struct_linked_list_numbers.html", "struct_linked_list_numbers" ],
    [ "LinkedListStrings", "struct_linked_list_strings.html", "struct_linked_list_strings" ],
    [ "modulation", "structmodulation.html", "structmodulation" ],
    [ "NumberArrayReference", "struct_number_array_reference.html", "struct_number_array_reference" ],
    [ "NumberReference", "struct_number_reference.html", "struct_number_reference" ],
    [ "PHYS", "struct_p_h_y_s.html", "struct_p_h_y_s" ],
    [ "PNGImage", "struct_p_n_g_image.html", "struct_p_n_g_image" ],
    [ "Rectangle", "struct_rectangle.html", "struct_rectangle" ],
    [ "RGBA", "struct_r_g_b_a.html", "struct_r_g_b_a" ],
    [ "RGBABitmap", "struct_r_g_b_a_bitmap.html", "struct_r_g_b_a_bitmap" ],
    [ "RGBABitmapImage", "struct_r_g_b_a_bitmap_image.html", "struct_r_g_b_a_bitmap_image" ],
    [ "RGBABitmapImageReference", "struct_r_g_b_a_bitmap_image_reference.html", "struct_r_g_b_a_bitmap_image_reference" ],
    [ "ScatterPlotSeries", "struct_scatter_plot_series.html", "struct_scatter_plot_series" ],
    [ "ScatterPlotSettings", "struct_scatter_plot_settings.html", "struct_scatter_plot_settings" ],
    [ "StringArrayReference", "struct_string_array_reference.html", "struct_string_array_reference" ],
    [ "StringReference", "struct_string_reference.html", "struct_string_reference" ],
    [ "UNITY_STORAGE_T", "struct_u_n_i_t_y___s_t_o_r_a_g_e___t.html", "struct_u_n_i_t_y___s_t_o_r_a_g_e___t" ],
    [ "ZLIBStruct", "struct_z_l_i_b_struct.html", "struct_z_l_i_b_struct" ]
];